### 长盈2025年第一期个人汽车抵押贷款

In [4]:
from absbox import Generic,readAeson

CHANGYING2501 = Generic(
    "CHANGYING2501/长盈2025年第一期个人汽车抵押贷款"
    ,{"cutoff":"2024-10-01","closing":"2025-01-09","firstPay":"2025-02-26","firstCollect":'2024-10-31'
     ,"payFreq":["DayOfMonth",26],"poolFreq":"MonthEnd","stated":"2032-10-26"
     ,"cust":{"buy":"2025-02-01"}}
    ,{'发行':{'资产池规模':2_902_361_192.68}
      ,'清单':[]
      ,'归集表':[['2024-10-31', 2807531499.13, 94829693.55, 12717534.27],
                 ['2024-11-30', 2712138885.92, 95392613.21, 12983154.05],
                 ['2024-12-31', 2623011194.2, 89127691.72, 12682000.3],
                 ['2025-01-31', 2534889563.58, 88121630.62, 12381969.17],
                 ['2025-02-28', 2447214530.08, 87675033.5, 12084760.77],
                 ['2025-03-31', 2359530062.5, 87684467.58, 11788815.78],
                 ['2025-04-30', 2272092276.36, 87437786.14, 11492185.43],
                 ['2025-05-31', 2184835409.06, 87256867.3, 11196015.0],
                 ['2025-06-30', 2097774019.1, 87061389.96, 10899799.42],
                 ['2025-07-31', 2011116932.27, 86657086.83, 10603505.5],
                 ['2025-08-31', 1924800370.2, 86316562.07, 10308213.41],
                 ['2025-09-30', 1838926467.88, 85873902.32, 10013875.56],
                 ['2025-10-31', 1753540655.55, 85385812.33, 9720530.48],
                 ['2025-11-30', 1668649897.52, 84890758.03, 9428000.63],
                 ['2025-12-31', 1590276332.52, 78373565.0, 9135263.35],
                 ['2026-01-31', 1516329393.61, 73946938.91, 8843805.37],
                 ['2026-02-28', 1447582370.15, 68747023.46, 8553394.22],
                 ['2026-03-31', 1381160556.56, 66421813.59, 8266476.45],
                 ['2026-04-30', 1317190823.17, 63969733.39, 7979823.11],
                 ['2026-05-31', 1255325954.88, 61864868.29, 7694167.55],
                 ['2026-06-30', 1196817279.83, 58508675.05, 7409438.24],
                 ['2026-07-31', 1141604845.82, 55212434.01, 7126097.27],
                 ['2026-08-31', 1089528852.69, 52075993.13, 6843292.1],
                 ['2026-09-30', 1039635381.08, 49893471.61, 6560875.33],
                 ['2026-10-31', 989978847.43, 49656533.65, 6279237.08],
                 ['2026-11-30', 940420262.78, 49558584.65, 5997447.4],
                 ['2026-12-31', 892869686.65, 47550576.13, 5715550.85],
                 ['2027-01-31', 847785376.21, 45084310.44, 5443177.49],
                 ['2027-02-28', 806016845.9, 41768530.31, 5182700.65],
                 ['2027-03-31', 765268032.77, 40748813.13, 4938915.37],
                 ['2027-04-30', 726277779.28, 38990253.49, 4700020.0],
                 ['2027-05-31', 688893572.13, 37384207.15, 4470101.13],
                 ['2027-06-30', 652979957.48, 35913614.65, 4248834.58],
                 ['2027-07-31', 618863203.46, 34116754.02, 4035513.85],
                 ['2027-08-31', 586536783.99, 32326419.47, 3830692.15],
                 ['2027-09-30', 555567524.36, 30969259.63, 3633793.65],
                 ['2027-10-31', 524588346.45, 30979177.91, 3443602.95],
                 ['2027-11-30', 493508004.62, 31080341.83, 3253276.83],
                 ['2027-12-31', 462586466.13, 30921538.49, 3062195.61],
                 ['2028-01-31', 431705298.24, 30881167.89, 2872001.81],
                 ['2028-02-28', 400961553.7, 30743744.54, 2681975.97],
                 ['2028-03-31', 370126509.23, 30835044.47, 2492606.42],
                 ['2028-04-30', 339311719.16, 30814790.07, 2302512.02],
                 ['2028-05-31', 308508915.19, 30802803.97, 2112376.38],
                 ['2028-06-30', 277689555.38, 30819359.81, 1922189.09],
                 ['2028-07-31', 246862833.36, 30826722.02, 1731747.88],
                 ['2028-08-31', 216104149.21, 30758684.15, 1541073.13],
                 ['2028-09-30', 185464651.32, 30639497.89, 1350724.8],
                 ['2028-10-31', 154757404.5, 30707246.82, 1161117.68],
                 ['2028-11-30', 124016296.93, 30741107.57, 971424.45],
                 ['2028-12-31', 97005492.69, 27010804.24, 781033.49],
                 ['2029-01-31', 74607025.26, 22398467.43, 613477.46],
                 ['2029-02-28', 56574919.03, 18032106.23, 473033.38],
                 ['2029-03-31', 40428420.62, 16146498.41, 359097.52],
                 ['2029-04-30', 26732804.0, 13695616.62, 257083.7],
                 ['2029-05-31', 15590826.65, 11141977.35, 170157.06],
                 ['2029-06-30', 7599880.29, 7990946.36, 99080.39],
                 ['2029-07-31', 2418340.01, 5181540.28, 48524.22],
                 ['2029-08-31', 76036.26, 2342303.75, 15517.23],
                 ['2029-09-30', 0.0, 76036.26, 514.92]]
     }
    ,(("收入账户",{"balance":0}),("本金账户",{"balance":0})
      ,("储备账户",{"balance":29_023_611.92
                   ,"type":{"when":[
                               [("isOutstanding","优先级"),True]
                              ,("target",("max",("factor",("poolBalance",),0.01),("factor",("originalPoolBalance",),0.005)))
                              ,{"fixReserve":0}]
                           }}
                ))
    ,(("优先级",{"balance":2_460_000_000.0
             ,"rate":0.017
             ,"originBalance":2_460_000_000.0
             ,"originRate":0.017
             ,"startDate":"2025-01-09"
             ,"rateType":{"Fixed":0.017}
             ,"maturityDate":"2028-04-26" 
             ,"bondType":"Sequential"})
      ,("次级",{"balance":270_000_000
             ,"rate":0.0
             ,"originBalance":270_000_000
             ,"originRate":0.00
             ,"startDate":"2025-01-09"
              ,"maturityDate":"2028-12-26" 
             ,"rateType":{"Fixed":0.00}
             ,"bondType":"Equity"
             }))
    ,(("增值税",{"type":{"targetBalanceFee":[("*",("资产池累计",None,"利息"),0.0326)
                                   ,("feeTxnAmt",None,"增值税")]}})
      ,("受托机构费用",{"type":{"annualPctFee":[("资产池余额",),0.0002]}})
      ,("服务商费用",{"type":{"annualPctFee":[("资产池余额",),0.0002]}})
     )
    ,{"default":[
         # 收入账户
         ["transfer","储备账户","收入账户",{"ds":("reserveExcess","储备账户")}]
         ,["calcAndPayFee","收入账户",['增值税'],{"support":["support",["account","储备账户"],["account","本金账户",("Debit","ABCD")]]}]
         ,["calcAndPayFee","收入账户",['受托机构费用'],{"limit":{"balCapAmt":50000},"support":["support",["account","储备账户"],["account","本金账户",("Debit","ABCD")]]}]
         ,["accrueAndPayInt","收入账户",["优先级"],{"support":["support",["account","储备账户"],["account","本金账户",("Debit","ABCD")]]}]
         ,["transfer","收入账户","储备账户",{"ds":("reserveGap","储备账户")}]
         ,["transfer","收入账户","本金账户",{"ds":("ledgerBalance","Debit","ABCD")},"book","Credit","ABCD"]
         ,["calcAndPayFee","收入账户",['服务商费用']]
         ,["payFee","收入账户",['受托机构费用'],]  
         ,["IfElse",["status", "Accelerated"]
            ,[["transfer","收入账户","本金账户"]]
            ,[["if",["status", "Amortizing"]
                ,["payIntResidual","收入账户","次级"]]
            ]
          ]
         # 本金账户
         ,["payPrin","本金账户",["优先级"]]
         ,["payPrin","本金账户",["次级"]]
         ,["payIntResidual","本金账户","次级"]
         ,["payIntResidual","收入账户","次级"]]
      ,"cleanUp":[
          ["transferM",["收入账户","储备账户"],"本金账户"]
          ,["calcAndPayFee","本金账户",['增值税','服务商费用','受托机构费用'],]
          ,["accrueAndPayInt","本金账户",["优先级"]]
          ,["payPrinBySeq","本金账户",["优先级","次级"]]
          ,["payIntResidual","本金账户","次级"]
      ]
      ,"endOfCollection":[
          ["bookBy", ["formula","ABCD","Debit",("curPoolCollection", None, "Defaults")]]
      ]
      ,("custom","buy"):[["buyAsset",["Current|Defaulted", 1.0, 0],"本金账户"]]
     }
    ,[["CollectedInterest","收入账户"]
      ,["CollectedPrincipal","本金账户"]
      ,["CollectedPrepayment","本金账户"]
      ,["CollectedRecoveries","本金账户"]]
    ,None
    ,None
    ,None
    ,{"AfterCollect":
       {"trg01":{"condition":["periodRateCurve", ("cumPoolDefaultedRate",)
                                       , ">", ("dealStat","int","BondPaidPeriod")
                                       ,[[0,0.02]
                                        ,[12,0.05]]
                             ]
                ,"effects":("newStatus","Defaulted")
                ,"status":False
                ,"curable":False}}}
    ,("PreClosing","Amortizing")
    ,None
    ,{"ABCD":{"balance":0}}
    ,None
    )

revol_asset = ["Mortgage"
                ,{"originBalance":2200,"originRate":["fix",0.055],"originTerm":46
                  ,"freq":"Monthly","type":"Level","originDate":"2021-02-01"}
                  ,{"currentBalance":2200
                  ,"currentRate":0.055
                  ,"remainTerm":40
                  ,"status":"current"}]

In [6]:
from absbox import API,EnginePath,compResult
localAPI = API(EnginePath.LOCAL,check=False)

Connecting engine server -> http://localhost:8081

✅Connected, local lib:0.28.7, server:0.43.0

In [9]:
%load_ext autoreload
%autoreload 2

revol_asset = ["Mortgage"
                ,{"originBalance":2200,"originRate":["fix",0.055],"originTerm":46
                  ,"freq":"Monthly","type":"Level","originDate":"2021-02-01"}
                  ,{"currentBalance":2200
                  ,"currentRate":0.055
                  ,"remainTerm":40
                  ,"status":"current"}]

In [99]:
r1 = localAPI.run(CHANGYING2501
                 ,runAssump = [("revolving"
                                 ,["constant",revol_asset]
                                 ,("Pool",("Mortgage",{"CDR":0.33143830048815853},None,None,None)
                                           ,None
                                           ,None))
                              ]
                 ,poolAssump = ("Pool",("Mortgage",{"CDR":0.11081276682938618},None,None,None)
                                       ,None
                                       ,None)
                 ,read=True)

r2 = localAPI.run(CHANGYING2501
                 ,runAssump = [("revolving"
                                 ,["constant",revol_asset]
                                 ,("Pool",("Mortgage",{"CDR":0.0143},None,None,None)
                                           ,None
                                           ,None))
                              ]
                 ,poolAssump = ("Pool",("Mortgage",{"CDR":0.11081276682938618},None,None,None)
                                       ,None
                                       ,None)
                 ,read=True)

Warning Message from server:
Bond 次级 is not paid off
Fee 服务商费用 is not paid off

Warning Message from server:
Bond 次级 is not paid off
Fee 服务商费用 is not paid off

In [112]:
dif = compResult(r1,r2,names=("highCDR","lowCDR"))

In [118]:
dif['bond']['次级'][['balance','cash']]

                 balance                                     cash  \
                 highCDR        lowCDR          diff      highCDR
date
2028-07-26  2.700000e+08  2.696383e+08  3.617319e+05         0.00
2028-08-26  2.700000e+08  2.344061e+08  3.559390e+07         0.00
2028-09-26  2.700000e+08  2.140507e+08  5.594928e+07         0.00
2028-10-26  2.700000e+08  1.940804e+08  7.591962e+07         0.00
2028-11-26  2.700000e+08  1.743799e+08  9.562013e+07         0.00
2028-12-26  2.700000e+08  1.549603e+08  1.150397e+08         0.00
2029-01-26  2.700000e+08  1.381091e+08  1.318909e+08         0.00
2029-02-26  2.700000e+08  1.242939e+08  1.457061e+08         0.00
2029-03-26  2.700000e+08  1.132836e+08  1.567164e+08         0.00
2029-04-26  2.700000e+08  1.035593e+08  1.664407e+08         0.00
2029-05-26  2.700000e+08  9.541714e+07  1.745829e+08         0.00
2029-06-26  2.700000e+08  8.888066e+07  1.811193e+08         0.00
2029-07-26  2.700000e+08  8.425049e+07  1.857495e+08         0.00
2029-08-26  2.700000e+08  8.128658e+07  1.887134e+08         0.00
2029-09-26  2.696106e+08  7.996354e+07  1.896470e+08    389424.23
2029-10-26  2.550562e+08  7.992099e+07  1.751352e+08  14554348.34
2029-10-31  2.550562e+08  7.992099e+07  1.751352e+08          NaN


                 lowCDR         diff
date
2028-07-26    361731.90   -361731.90
2028-08-26  35232166.72 -35232166.72
2028-09-26  20355381.42 -20355381.42
2028-10-26  19970338.67 -19970338.67
2028-11-26  19700507.50 -19700507.50
2028-12-26  19419621.88 -19419621.88
2029-01-26  16851175.57 -16851175.57
2029-02-26  13815128.81 -13815128.81
2029-03-26  11010316.54 -11010316.54
2029-04-26   9724299.13  -9724299.13
2029-05-26   8142195.99  -8142195.99
2029-06-26   6536475.43  -6536475.43
2029-07-26   4630173.55  -4630173.55
2029-08-26   2963906.06  -2963906.06
2029-09-26   1323045.68   -933621.45
2029-10-26     42542.37  14511805.97
2029-10-31          NaN         0.00

In [116]:
r1['fees']['服务商费用']

              balance  payment  due
date
2025-02-26   30707.41        0    0
2025-03-26   33771.60        0    0
2025-04-26   41143.31        0    0
2025-05-26   46767.31        0    0
2025-06-26   53462.45        0    0
2025-07-26   58556.15        0    0
2025-08-26   64603.71        0    0
2025-09-26   70338.82        0    0
2025-10-26   74682.44        0    0
2025-11-26   79815.63        0    0
2025-12-26   83690.62        0    0
2026-01-26   88253.03        0    0
2026-02-26   92554.98        0    0
2026-03-26   94177.78        0    0
2026-04-26   98010.57        0    0
2026-05-26  100904.20        0    0
2026-06-26  104315.33        0    0
2026-07-26  106886.54        0    0
2026-08-26  109915.76        0    0
2026-09-26  112771.12        0    0
2026-10-26  114924.66        0    0
2026-11-26  117462.31        0    0
2026-12-26  119371.87        0    0
2027-01-26  121612.11        0    0
2027-02-26  123712.78        0    0
2027-03-26  124500.44        0    0
2027-04-26  126349.57        0    0
2027-05-26  127735.85        0    0
2027-06-26  129358.54        0    0
2027-07-26  130572.92        0    0
2027-08-26  131991.79        0    0
2027-09-26  133317.09        0    0
2027-10-26  134306.92        0    0
2027-11-26  135461.23        0    0
2027-12-26  136319.64        0    0
2028-01-26  137313.29        0    0
2028-02-26  138229.50        0    0
2028-03-26  138733.86        0    0
2028-04-26  139501.62        0    0
2028-05-26  140058.06        0    0
2028-06-26  140683.49        0    0
2028-07-26  141128.92        0    0
2028-08-26  141618.80        0    0
2028-09-26  142049.98        0    0
2028-10-26  142348.94        0    0
2028-11-26  142666.58        0    0
2028-12-26  142876.51        0    0
2029-01-26  143084.78        0    0
2029-02-26  143246.07        0    0
2029-03-26  143295.19        0    0
2029-04-26  143387.49        0    0
2029-05-26  143439.73        0    0
2029-06-26  143482.49        0    0
2029-07-26  143502.24        0    0
2029-08-26  143514.16        0    0
2029-09-26  143517.91        0    0
2029-10-26  143518.00        0    0
2029-10-31  143518.00        0    0

In [23]:
def compDf(x, y):
    #return pd.merge(x, y, on="Date", how='outer').sort_index().sort_index(axis=1)
    return x.compare(y, result_names=("Left","Right"))

import pandas as pd

df = r1['pool']['flow']['PoolConsol']-r2['pool']['flow']['PoolConsol']
df

,Balance,Principal,Interest,Prepayment,Default,Recovery,Loss,WAC,BorrowerNum,PrepayPenalty,CumPrincipal,CumPrepay,CumDelinq,CumDefault,CumRecovery,CumLoss
Date,,,,,,,,,,,,,,,,
2025-01-09,0.00,0.00,0.00,0,0.00,0,0.00,0.000000,NaN,NaN,0.000000e+00,0,0,0.000000e+00,0,0.000000e+00
2025-01-31,0.00,0.00,0.00,0,0.00,0,0.00,0.000000,NaN,NaN,0.000000e+00,0,0,0.000000e+00,0,0.000000e+00
2025-02-28,0.00,0.00,0.00,0,0.00,0,0.00,0.000000,NaN,NaN,0.000000e+00,0,0,0.000000e+00,0,0.000000e+00
2025-03-31,-10275492.58,-240130.11,-48193.10,0,10515622.69,0,10515622.69,0.000002,NaN,NaN,-2.401301e+05,0,0,1.051562e+07,0,1.051562e+07
2025-04-30,-20775117.67,-499448.26,-97501.34,0,10999073.35,0,10999073.35,0.000005,NaN,NaN,-7.395784e+05,0,0,2.151470e+07,0,2.151470e+07
2025-05-31,-30068517.65,-744152.89,-141214.47,0,10037552.87,0,10037552.87,0.000008,NaN,NaN,-1.483731e+06,0,0,3.155225e+07,0,3.155225e+07
2025-06-30,-38851770.60,-990559.84,-182597.40,0,9773812.79,0,9773812.79,0.000010,NaN,NaN,-2.474291e+06,0,0,4.132606e+07,0,4.132606e+07
2025-07-31,-46534512.12,-1223205.11,-218873.61,0,8905946.63,0,8905946.63,0.000014,NaN,NaN,-3.697496e+06,0,0,5.023201e+07,0,5.023201e+07
2025-08-31,-53735214.67,-1457441.88,-252947.94,0,8658144.43,0,8658144.43,0.000016,NaN,NaN,-5.154938e+06,0,0,5.889015e+07,0,5.889015e+07
2025-09-30,-60183433.50,-1685747.18,-283546.46,0,8133966.01,0,8133966.01,0.000020,NaN,NaN,-6.840685e+06,0,0,6.702412e+07,0,6.702412e+07
2025-10-31,-65674436.22,-1901486.71,-309700.45,0,7392489.43,0,7392489.43,0.000025,NaN,NaN,-8.742172e+06,0,0,7.441661e+07,0,7.441661e+07
2025-11-30,-70722844.82,-2118662.04,-333832.63,0,7167070.64,0,7167070.64,0.000028,NaN,NaN,-1.086083e+07,0,0,8.158368e+07,0,8.158368e+07
2025-12-31,-74899560.44,-2324008.20,-353915.61,0,6500723.82,0,6500723.82,0.000031,NaN,NaN,-1.318484e+07,0,0,8.808440e+07,0,8.808440e+07
2026-01-31,-78657980.90,-2530694.18,-372087.70,0,6289114.64,0,6289114.64,0.000034,NaN,NaN,-1.571554e+07,0,0,9.437352e+07,0,9.437352e+07
2026-02-28,-81803526.05,-2732268.24,-387427.55,0,5877813.39,0,5877813.39,0.000037,NaN,NaN,-1.844780e+07,0,0,1.002513e+08,0,1.002513e+08
2026-03-31,-83856365.83,-2911356.11,-397656.47,0,4964195.89,0,4964195.89,0.000040,NaN,NaN,-2.135916e+07,0,0,1.052155e+08,0,1.052155e+08
2026-04-30,-85885038.90,-3103703.21,-407835.41,0,5132376.28,0,5132376.28,0.000043,NaN,NaN,-2.446286e+07,0,0,1.103479e+08,0,1.103479e+08
2026-05-31,-87225211.87,-3285868.99,-414812.29,0,4626041.96,0,4626041.96,0.000048,NaN,NaN,-2.774873e+07,0,0,1.149739e+08,0,1.149739e+08
2026-06-30,-88201473.15,-3469159.47,-420126.51,0,4445420.75,0,4445420.75,0.000050,NaN,NaN,-3.121789e+07,0,0,1.194194e+08,0,1.194194e+08
2026-07-31,-88552595.42,-3642871.20,-422531.83,0,3993993.47,0,3993993.47,0.000054,NaN,NaN,-3.486076e+07,0,0,1.234134e+08,0,1.234134e+08
2026-08-31,-88559690.83,-3817628.85,-423365.26,0,3824724.26,0,3824724.26,0.000056,NaN,NaN,-3.867839e+07,0,0,1.272381e+08,0,1.272381e+08
2026-09-30,-88106888.08,-3988228.55,-422071.92,0,3535425.80,0,3535425.80,0.000059,NaN,NaN,-4.266662e+07,0,0,1.307735e+08,0,1.307735e+08
2026-10-31,-87114450.01,-4150095.56,-418265.41,0,3157657.49,0,3157657.49,0.000064,NaN,NaN,-4.681672e+07,0,0,1.339312e+08,0,1.339312e+08
2026-11-30,-85805910.04,-4312897.73,-413014.50,0,3004357.76,0,3004357.76,0.000070,NaN,NaN,-5.112961e+07,0,0,1.369355e+08,0,1.369355e+08
2026-12-31,-84008546.48,-4467488.40,-405485.67,0,2670124.84,0,2670124.84,0.000073,NaN,NaN,-5.559710e+07,0,0,1.396056e+08,0,1.396056e+08
2027-01-31,-81912298.43,-4622945.91,-396591.03,0,2526697.86,0,2526697.86,0.000077,NaN,NaN,-6.022005e+07,0,0,1.421323e+08,0,1.421323e+08
2027-02-28,-79442592.52,-4774824.83,-385968.42,0,2305118.92,0,2305118.92,0.000076,NaN,NaN,-6.499487e+07,0,0,1.444375e+08,0,1.444375e+08
2027-03-31,-76427479.73,-4911192.27,-372775.14,0,1896079.48,0,1896079.48,0.000081,NaN,NaN,-6.990607e+07,0,0,1.463335e+08,0,1.463335e+08
2027-04-30,-73274990.73,-5056619.53,-358993.77,0,1904130.53,0,1904130.53,0.000083,NaN,NaN,-7.496269e+07,0,0,1.482377e+08,0,1.482377e+08
2027-05-31,-69741834.52,-5195001.57,-343435.52,0,1661845.36,0,1661845.36,0.000086,NaN,NaN,-8.015769e+07,0,0,1.498995e+08,0,1.498995e+08
2027-06-30,-65948379.49,-5334097.15,-326687.59,0,1540642.12,0,1540642.12,0.000088,NaN,NaN,-8.549178e+07,0,0,1.514402e+08,0,1.514402e+08
2027-07-31,-61811355.79,-5466574.07,-308334.75,0,1329550.37,0,1329550.37,0.000089,NaN,NaN,-9.095836e+07,0,0,1.527697e+08,0,1.527697e+08
2027-08-31,-57428159.54,-5599708.34,-288856.72,0,1216512.09,0,1216512.09,0.000089,NaN,NaN,-9.655807e+07,0,0,1.539862e+08,0,1.539862e+08
2027-09-30,-52765719.52,-5729938.55,-268085.61,0,1067498.53,0,1067498.53,0.000089,NaN,NaN,-1.022880e+08,0,0,1.550537e+08,0,1.550537e+08
2027-10-31,-47809457.46,-5854149.14,-245940.31,0,897887.08,0,897887.08,0.000092,NaN,NaN,-1.081422e+08,0,0,1.559516e+08,0,1.559516e+08
2027-11-30,-42626880.47,-5978938.03,-222760.47,0,796361.04,0,796361.04,0.000094,NaN,NaN,-1.141211e+08,0,0,1.567480e+08,0,1.567480e+08
2027-12-31,-37179859.15,-6098076.42,-198342.77,0,651055.10,0,651055.10,0.000094,NaN,NaN,-1.202192e+08,0,0,1.573990e+08,0,1.573990e+08
2028-01-31,-31518781.16,-6217744.28,-172946.49,0,556666.29,0,556666.29,0.000093,NaN,NaN,-1.264369e+08,0,0,1.579557e+08,0,1.579557e+08
2028-02-29,-25631334.18,-6334917.82,-146501.33,0,447470.84,0,447470.84,0.000088,NaN,NaN,-1.327718e+08,0,0,1.584032e+08,0,1.584032e+08
2028-03-31,-19510471.54,-6444241.91,-118950.45,0,323379.27,0,323379.27,0.000082,NaN,NaN,-1.392161e+08,0,0,1.587265e+08,0,1.587265e+08
2028-04-30,-13203958.25,-6556835.31,-90563.71,0,250322.02,0,250322.02,0.000068,NaN,NaN,-1.457729e+08,0,0,1.589769e+08,0,1.589769e+08
2028-05-31,-6695154.16,-6664610.24,-61227.80,0,155806.15,0,155806.15,0.000043,NaN,NaN,-1.524375e+08,0,0,1.591327e+08,0,1.591327e+08
2028-06-30,0.00,-6772804.27,-31039.77,0,77650.11,0,77650.11,0.000000,NaN,NaN,-1.592103e+08,0,0,1.592103e+08,0,1.592103e+08
2028-07-31,0.00,0.00,0.00,0,0.00,0,0.00,0.000000,NaN,NaN,-1.592103e+08,0,0,1.592103e+08,0,1.592103e+08
2028-08-31,0.00,0.00,0.00,0,0.00,0,0.00,0.000000,NaN,NaN,-1.592103e+08,0,0,1.592103e+08,0,1.592103e+08
2028-09-30,0.00,0.00,0.00,0,0.00,0,0.00,0.000000,NaN,NaN,-1.592103e+08,0,0,1.592103e+08,0,1.592103e+08
2028-10-31,0.00,0.00,0.00,0,0.00,0,0.00,0.000000,NaN,NaN,-1.592103e+08,0,0,1.592103e+08,0,1.592103e+08
2028-11-30,0.00,0.00,0.00,0,0.00,0,0.00,0.000000,NaN,NaN,-1.592103e+08,0,0,1.592103e+08,0,1.592103e+08
2028-12-31,0.00,0.00,0.00,0,0.00,0,0.00,0.000000,NaN,NaN,-1.592103e+08,0,0,1.592103e+08,0,1.592103e+08
2029-01-31,0.00,0.00,0.00,0,0.00,0,0.00,0.000000,NaN,NaN,-1.592103e+08,0,0,1.592103e+08,0,1.592103e+08
2029-02-28,0.00,0.00,0.00,0,0.00,0,0.00,0.000000,NaN,NaN,-1.592103e+08,0,0,1.592103e+08,0,1.592103e+08
2029-03-31,0.00,0.00,0.00,0,0.00,0,0.00,0.000000,NaN,NaN,-1.592103e+08,0,0,1.592103e+08,0,1.592103e+08
2029-04-30,0.00,0.00,0.00,0,0.00,0,0.00,0.000000,NaN,NaN,-1.592103e+08,0,0,1.592103e+08,0,1.592103e+08
2029-05-31,0.00,0.00,0.00,0,0.00,0,0.00,0.000000,NaN,NaN,-1.592103e+08,0,0,1.592103e+08,0,1.592103e+08
2029-06-30,0.00,0.00,0.00,0,0.00,0,0.00,0.000000,NaN,NaN,-1.592103e+08,0,0,1.592103e+08,0,1.592103e+08
2029-07-31,0.00,0.00,0.00,0,0.00,0,0.00,0.000000,NaN,NaN,-1.592103e+08,0,0,1.592103e+08,0,1.592103e+08
2029-08-31,0.00,0.00,0.00,0,0.00,0,0.00,0.000000,NaN,NaN,-1.592103e+08,0,0,1.592103e+08,0,1.592103e+08
2029-09-30,0.00,0.00,0.00,0,0.00,0,0.00,0.000000,NaN,NaN,-1.592103e+08,0,0,1.592103e+08,0,1.592103e+08

In [66]:
import pandas as pd

data1 = {
  "calories": [420, 380,300.1],
  "duration": [True, False,True]
}

data2 = {
  "calories": [300, 210, 390],
  "duration": [True, True, True]
}

#load data into a DataFrame object:
df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)

diff = df1.compare(df2)
diff

  calories       duration
      self other     self other
0    420.0   300      NaN   NaN
1    380.0   210    False  True
2    300.1   390      NaN   NaN

In [67]:
result = diff.copy()

for column in diff.columns.levels[0]:
    print("column", column,type(diff[column]['self']),diff[column]['self'].dtype)
    result[column, '_diff'] = diff[column]['self'].fillna(0) - diff[column]['other'].fillna(0)

result

column calories <class 'pandas.core.series.Series'> float64
column duration <class 'pandas.core.series.Series'> object

  calories       duration       calories duration
      self other     self other    _diff    _diff
0    420.0   300      NaN   NaN    120.0        0
1    380.0   210    False  True    170.0       -1
2    300.1   390      NaN   NaN    -89.9        0

In [59]:
result.sort_index(axis=1,ascending=False)

  duration               calories
      self  other  _diff     self other _diff
0      NaN    NaN    0.0      420   300   120
1      NaN    NaN    0.0      380   210   170
2     10.0  145.0 -135.0      300   390   -90

In [36]:
diff.columns

MultiIndex([('calories',  'self'),
            ('calories', 'other'),
            ('duration',  'self'),
            ('duration', 'other')],
           )

In [ ]:
def compDf(x, y):
    (nameA,namesB) = ("Left","Right")
    cmp = x.compare(y, result_names=(nameA,namesB))
    result = cmp.copy()
    for column in cmp.columns.levels[0]:
        result[column, '_diff'] = cmp[column][nameA].fillna(0) - cmp[column][namesB].fillna(0)
    return result.sort_index(axis=1,ascending=False)

In [41]:
df1 = df1.compare(df2, result_names=("Left","Right"))

result = df1.copy()

# Add differences in one go using MultiIndex
new_columns = pd.MultiIndex.from_tuples(
    [(col, 'diff') for col in df1.columns.levels[0]]
)
diff_values = df1.xs('Left', level=1, axis=1) - df2.xs('Right', level=1, axis=1)
result = pd.concat([result, diff_values.set_axis(new_columns, axis=1)], axis=1)

# Sort columns for better readability (optional)
result = result.sort_index(axis=1)

print(result)

TypeError: Index must be a MultiIndex