In [1]:
from absbox.local.generic import Generic

test03 = Generic(
    "If in Waterfall"
    ,{"cutoff":"2021-03-01","closing":"2021-06-15","firstPay":"2021-07-26"
     ,"payFreq":["DayOfMonth",20],"poolFreq":"MonthEnd","stated":"2030-01-01"}
    ,{'assets':[["Mortgage"
        ,{"originBalance":2200,"originRate":["fix",0.045],"originTerm":30
          ,"freq":"Monthly","type":"Level","originDate":"2021-02-01"}
          ,{"currentBalance":2200
          ,"currentRate":0.08
          ,"remainTerm":20
          ,"status":"current"}]]}
    ,(("acc01",{"balance":0}),)
    ,(("A1",{"balance":500
             ,"rate":0.07
             ,"originBalance":500
             ,"originRate":0.07
             ,"startDate":"2020-01-03"
             ,"maturityDate":"2022-03-31"
             ,"rateType":{"Fixed":0.08}
             ,"bondType":{"Sequential":None}})
      ,("A2",{"balance":500
             ,"rate":0.07
             ,"originBalance":500
             ,"originRate":0.07
             ,"startDate":"2020-01-03"
             ,"rateType":{"Fixed":0.08}
             ,"bondType":{"Sequential":None}})
      ,("B",{"balance":1000
             ,"rate":0.0
             ,"originBalance":1000
             ,"originRate":0.07
             ,"startDate":"2020-01-03"
             ,"rateType":{"Fixed":0.00}
             ,"bondType":{"Equity":None}
             }))
    ,(("trusteeFee",{"type":{"fixFee":30}}),)
    ,{"amortizing":[
         ["payFee",["acc01"],['trusteeFee']]
         ,["payInt","acc01",["A1","A2"]]
         ,[[("monthsTillMaturity","A1"),"<",3]
           ,["payPrin","acc01",["A1","A2"]]
           ]
         ,["payPrin","acc01",["B"]]
         ,["payResidual","acc01","B"]]
      }
    ,[["CollectedInterest","acc01"]
      ,["CollectedPrincipal","acc01"]
      ,["CollectedPrepayment","acc01"]
      ,["CollectedRecoveries","acc01"]]
    ,None
    ,None
    ,None
    ,None
    )

In [2]:
from absbox import API
localAPI = API("https://absbox.org/api/latest")

In [3]:
r = localAPI.run(test03
                 ,assumptions=[{"Inspect":[("MonthEnd",("poolBalance",)),("MonthFirst",("bondBalance",))]}],read=True)

In [4]:
from absbox.local.util import *

In [6]:
r['result']['inspect']

{'<CurrentBondBalance>':             <CurrentBondBalance>
 Date
 2021-03-01               2000.00
 2021-04-01               2000.00
 2021-05-01               2000.00
 2021-06-01               2000.00
 2021-07-01               2000.00
 2021-08-01               1694.72
 2021-09-01               1585.12
 2021-10-01               1476.68
 2021-11-01               1368.04
 2021-12-01               1259.60
 2022-01-01               1150.96
 2022-02-01               1042.52
 2022-03-01                933.44
 2022-04-01                823.26
 2022-05-01                712.86
 2022-06-01                601.70
 2022-07-01                490.00
 2022-08-01                377.58
 2022-09-01                264.54
 2022-10-01                150.82
 2022-11-01                 36.45
 2022-12-01                  0.00,
 '<CurrentPoolBalance>':             <CurrentPoolBalance>
 Date
 2021-03-01                  0.00
 2021-03-31                  0.00
 2021-04-30                  0.00
 2021-05-31                  0.00
 2021-06-30               1880.41
 2021-07-31               1773.08
 2021-08-31               1665.34
 2021-09-30               1557.20
 2021-10-31               1448.65
 2021-11-30               1339.70
 2021-12-31               1230.34
 2022-01-31               1120.57
 2022-02-28               1010.39
 2022-03-31                899.79
 2022-04-30                788.78
 2022-05-31                677.36
 2022-06-30                565.53
 2022-07-31                453.27
 2022-08-31                340.58
 2022-09-30                227.48
 2022-10-31                113.95
 2022-11-30                  0.00}

In [5]:
unifyTs(r['result']['inspect'].values())

            <CurrentBondBalance>  <CurrentPoolBalance>
Date
2021-03-01               2000.00                  0.00
2021-03-31                   NaN                  0.00
2021-04-01               2000.00                   NaN
2021-04-30                   NaN                  0.00
2021-05-01               2000.00                   NaN
2021-05-31                   NaN                  0.00
2021-06-01               2000.00                   NaN
2021-06-30                   NaN               1880.41
2021-07-01               2000.00                   NaN
2021-07-31                   NaN               1773.08
2021-08-01               1694.72                   NaN
2021-08-31                   NaN               1665.34
2021-09-01               1585.12                   NaN
2021-09-30                   NaN               1557.20
2021-10-01               1476.68                   NaN
2021-10-31                   NaN               1448.65
2021-11-01               1368.04                   NaN
2021-11-30                   NaN               1339.70
2021-12-01               1259.60                   NaN
2021-12-31                   NaN               1230.34
2022-01-01               1150.96                   NaN
2022-01-31                   NaN               1120.57
2022-02-01               1042.52                   NaN
2022-02-28                   NaN               1010.39
2022-03-01                933.44                   NaN
2022-03-31                   NaN                899.79
2022-04-01                823.26                   NaN
2022-04-30                   NaN                788.78
2022-05-01                712.86                   NaN
2022-05-31                   NaN                677.36
2022-06-01                601.70                   NaN
2022-06-30                   NaN                565.53
2022-07-01                490.00                   NaN
2022-07-31                   NaN                453.27
2022-08-01                377.58                   NaN
2022-08-31                   NaN                340.58
2022-09-01                264.54                   NaN
2022-09-30                   NaN                227.48
2022-10-01                150.82                   NaN
2022-10-31                   NaN                113.95
2022-11-01                 36.45                   NaN
2022-11-30                   NaN                  0.00
2022-12-01                  0.00                   NaN

In [17]:
list(set([1,2,3]))[0]

1