In [1]:
import pandas as pd
pd.set_option("display.max_row", None)
%load_ext autoreload
%autoreload 2

In [2]:
from absbox import API,EnginePath,Generic

localAPI = API(EnginePath.DEV,check=False)

test01 = Generic(
    "underlyingDeal"
    #,{"cutoff":"2021-03-01","closing":"2021-06-15","firstPay":"2021-07-26"
    # ,"payFreq":["DayOfMonth",20],"poolFreq":"MonthEnd","stated":"2030-01-01"}
    ,{"collect":["2022-11-01"   # last pool collection date,
                ,"2022-12-01"] # next pool collection date
        ,"pay":["2022-11-15"   # last distribution payment date,
                ,"2022-12-15"] # next distribution date
        ,"stated":"2030-01-01"
        ,"poolFreq":"MonthEnd"
        ,"payFreq":["DayOfMonth",20]
        }
    ,{'assets':[["Mortgage"
        ,{"originBalance":2200,"originRate":["fix",0.045],"originTerm":30
          ,"freq":"Monthly","type":"Level","originDate":"2021-02-01"}
          ,{"currentBalance":2200
          ,"currentRate":0.08
          ,"remainTerm":30
          ,"status":"current"}]]
     ,'issuanceStat':{"IssuanceBalance":2200}}
    ,(("acc01",{"balance":0}),)
    ,(("A1",{"balance":1000
             ,"rate":0.07
             ,"originBalance":1000
             ,"originRate":0.07
             ,"startDate":"2022-11-15"
             ,"rateType":{"Fixed":0.08}
             ,"bondType":{"Sequential":None}})
      ,("B",{"balance":1000
             ,"rate":0.0
             ,"originBalance":1000
             ,"originRate":0.07
             ,"startDate":"2022-11-15"
             ,"rateType":{"Fixed":0.00}
             ,"bondType":{"Equity":None}
             }))
    ,(("trusteeFee",{"type":{"fixFee":30}}),)
    ,{"amortizing":[
         ["payFee","acc01",['trusteeFee']]
         ,["accrueAndPayInt","acc01",["A1"]]
         ,["payPrin","acc01",["A1"]]
         ,["payPrin","acc01",["B"]]
         ,["payIntResidual","acc01","B"]
     ]}
    ,[["CollectedInterest","acc01"]
      ,["CollectedPrincipal","acc01"]
      ,["CollectedPrepayment","acc01"]
      ,["CollectedRecoveries","acc01"]]
    ,None
    ,None
    ,None
    ,None
    ,"Amortizing"
    )

test02 = Generic(
    "TEST01"
    ,{"cutoff":"2021-03-01","closing":"2021-06-15","firstPay":"2021-07-26"
     ,"payFreq":["DayOfMonth",20],"poolFreq":"MonthEnd","stated":"2030-01-01"}
    ,{'deals':
       {("A1",'1 % 1',"2022-03-31"):test01}}
    ,(("acc01",{"balance":0}),)
    ,(("A1",{"balance":1000
             ,"rate":0.07
             ,"originBalance":1000
             ,"originRate":0.07
             ,"startDate":"2020-01-03"
             ,"rateType":{"Fixed":0.08}
             ,"bondType":{"Sequential":None}})
      ,("B",{"balance":1000
             ,"rate":0.0
             ,"originBalance":1000
             ,"originRate":0.07
             ,"startDate":"2020-01-03"
             ,"rateType":{"Fixed":0.00}
             ,"bondType":{"Equity":None}
             }))
    ,(("trusteeFee",{"type":{"fixFee":30}}),)
    ,{"amortizing":[
         ["payFee","acc01",['trusteeFee']]
         ,["accrueAndPayInt","acc01",["A1"]]
         ,["payPrin","acc01",["A1"]]
         ,["payPrin","acc01",["B"]]
         ,["payIntResidual","acc01","B"]
     ]}
    ,[["CollectedInterest","acc01"]
      ,["CollectedPrincipal","acc01"]]
    ,None
    ,None
    ,None
    ,None
    ,("PreClosing","Amortizing")
    )

Connecting engine server -> https://absbox.org/api/dev

✅Connected, local lib:0.26.4, server:0.27.10

In [3]:
r0 = localAPI.run(test01
                 ,poolAssump = None
                 ,runAssump = []
                 ,read=True)

Warning Message from server:
Bond A1 is not paid off
Bond B is not paid off

In [4]:
r0['pool']['flow']

,Balance,Principal,Interest,Prepayment,Default,Recovery,Loss,WAC,BorrowerNum,PrepayPenalty,CumPrincipal,CumPrepay,CumDelinq,CumDefault,CumRecovery,CumLoss
Date,,,,,,,,,,,,,,,,
2022-12-01,630.16,152.36,9.92,0,0,0,0,0.08,None,None,152.36,0,0,0,0,0
2022-12-31,630.16,0.00,0.00,0,0,0,0,0.08,None,None,152.36,0,0,0,0,0
2023-01-31,553.21,76.95,4.20,0,0,0,0,0.08,None,None,229.31,0,0,0,0,0
2023-02-28,475.74,77.47,3.68,0,0,0,0,0.08,None,None,306.78,0,0,0,0,0
2023-03-31,397.76,77.98,3.17,0,0,0,0,0.08,None,None,384.76,0,0,0,0,0
2023-04-30,319.27,78.49,2.65,0,0,0,0,0.08,None,None,463.25,0,0,0,0,0
2023-05-31,240.24,79.03,2.12,0,0,0,0,0.08,None,None,542.28,0,0,0,0,0
2023-06-30,160.70,79.54,1.60,0,0,0,0,0.08,None,None,621.82,0,0,0,0,0
2023-07-31,80.62,80.08,1.07,0,0,0,0,0.08,None,None,701.90,0,0,0,0,0
2023-08-31,0.00,80.62,0.53,0,0,0,0,0.08,None,None,782.52,0,0,0,0,0

In [5]:
r0['bonds']['A1']

,balance,interest,principal,rate,cash,factor,memo
date,,,,,,,
2022-12-15,873.47,5.75,126.53,0.07,132.28,0.87347,"[<PayInt:A1>, <PayPrin:A1>]"
2022-12-20,873.47,0.00,0.00,0.07,0.00,0.87347,"[<PayInt:A1>, <PayPrin:A1>]"
2023-01-20,873.47,0.00,0.00,0.07,0.00,0.87347,"[<PayInt:A1>, <PayPrin:A1>]"
2023-02-20,803.56,11.24,69.91,0.07,81.15,0.80356,"[<PayInt:A1>, <PayPrin:A1>]"
2023-03-20,726.72,4.31,76.84,0.07,81.15,0.72672,"[<PayInt:A1>, <PayPrin:A1>]"
2023-04-20,649.89,4.32,76.83,0.07,81.15,0.64989,"[<PayInt:A1>, <PayPrin:A1>]"
2023-05-20,572.48,3.73,77.41,0.07,81.14,0.57248,"[<PayInt:A1>, <PayPrin:A1>]"
2023-06-20,494.73,3.40,77.75,0.07,81.15,0.49473,"[<PayInt:A1>, <PayPrin:A1>]"
2023-07-20,416.43,2.84,78.30,0.07,81.14,0.41643,"[<PayInt:A1>, <PayPrin:A1>]"
2023-08-20,337.75,2.47,78.68,0.07,81.15,0.33775,"[<PayInt:A1>, <PayPrin:A1>]"
2023-09-20,258.60,2.00,79.15,0.07,81.15,0.25860,"[<PayInt:A1>, <PayPrin:A1>]"

In [9]:
r = localAPI.run(test02
                 ,poolAssump = ("ByDealName"
                                ,{"underlyingDeal":(("Pool",("Mortgage",None,None,None,None)
                                               ,None,None)
                                             ,[]
                                             )})
                 ,runAssump = []
                 ,read=True)

Warning Message from server:
Bond A1 is not paid off
Bond B is not paid off

In [12]:
r['pool']['flow']['underlyingDeal', 'A1', '1 % 1']

            Balance  Principal  Interest
Date
2021-06-15  1000.00       0.00      0.00
2021-06-30  1000.00       0.00      0.00
2021-07-31  1000.00       0.00      0.00
2021-08-31  1000.00       0.00      0.00
2021-09-30  1000.00       0.00      0.00
2021-10-31  1000.00       0.00      0.00
2021-11-30  1000.00       0.00      0.00
2021-12-31  1000.00       0.00      0.00
2022-01-31  1000.00       0.00      0.00
2022-02-28  1000.00       0.00      0.00
2022-03-31  1000.00       0.00      0.00
2022-04-30  1000.00       0.00      0.00
2022-05-31  1000.00       0.00      0.00
2022-06-30  1000.00       0.00      0.00
2022-07-31  1000.00       0.00      0.00
2022-08-31  1000.00       0.00      0.00
2022-09-30  1000.00       0.00      0.00
2022-10-31  1000.00       0.00      0.00
2022-11-30  1000.00       0.00      0.00
2022-12-31   873.47     126.53      5.75
2023-01-31   873.47       0.00      0.00
2023-02-28   803.56      69.91     11.24
2023-03-31   726.72      76.84      4.31
2023-04-30   649.89      76.83      4.32
2023-05-31   572.48      77.41      3.73
2023-06-30   494.73      77.75      3.40
2023-07-31   416.43      78.30      2.84
2023-08-31   337.75      78.68      2.47
2023-09-30   258.60      79.15      2.00

In [99]:
r['pool']['flow'][('TEST0111', 'A1', '1 % 1')]

            Balance  Principal  Interest
Date
2021-06-15  1000.00       0.00      0.00
2021-06-30  1000.00       0.00      0.00
2021-07-31  1000.00       0.00      0.00
2021-08-31  1000.00       0.00      0.00
2021-09-30  1000.00       0.00      0.00
2021-10-31  1000.00       0.00      0.00
2021-11-30  1000.00       0.00      0.00
2021-12-31  1000.00       0.00      0.00
2022-01-31  1000.00       0.00      0.00
2022-02-28   932.54      67.46     48.93
2022-03-31   794.55     137.99      5.00
2022-04-30   662.03     132.52      4.72
2022-05-31   529.29     132.74      3.80
2022-06-30   399.83     129.46      3.14
2022-07-31   271.96     127.87      2.30
2022-08-31   147.12     124.84      1.61
2022-09-30    23.98     123.14      0.87
2022-10-31     0.00      23.98      0.13

In [7]:
r0['bonds']['A1']

,balance,interest,principal,rate,cash,factor,memo
date,,,,,,,
2022-12-15,873.47,5.75,126.53,0.07,132.28,0.87347,"[<PayInt:A1>, <PayPrin:A1>]"
2022-12-20,873.47,0.00,0.00,0.07,0.00,0.87347,"[<PayInt:A1>, <PayPrin:A1>]"
2023-01-20,873.47,0.00,0.00,0.07,0.00,0.87347,"[<PayInt:A1>, <PayPrin:A1>]"
2023-02-20,803.56,11.24,69.91,0.07,81.15,0.80356,"[<PayInt:A1>, <PayPrin:A1>]"
2023-03-20,726.72,4.31,76.84,0.07,81.15,0.72672,"[<PayInt:A1>, <PayPrin:A1>]"
2023-04-20,649.89,4.32,76.83,0.07,81.15,0.64989,"[<PayInt:A1>, <PayPrin:A1>]"
2023-05-20,572.48,3.73,77.41,0.07,81.14,0.57248,"[<PayInt:A1>, <PayPrin:A1>]"
2023-06-20,494.73,3.40,77.75,0.07,81.15,0.49473,"[<PayInt:A1>, <PayPrin:A1>]"
2023-07-20,416.43,2.84,78.30,0.07,81.14,0.41643,"[<PayInt:A1>, <PayPrin:A1>]"
2023-08-20,337.75,2.47,78.68,0.07,81.15,0.33775,"[<PayInt:A1>, <PayPrin:A1>]"
2023-09-20,258.60,2.00,79.15,0.07,81.15,0.25860,"[<PayInt:A1>, <PayPrin:A1>]"