### Master Trust/Warehousing Funding Example

In [66]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [50]:
from absbox import Generic,API,EnginePath,readBondsCf

test01 = Generic(
    "TEST01"
    ,{"cutoff":"2021-03-01","closing":"2021-06-15","firstPay":"2021-07-26"
     ,"payFreq":["DayOfMonth",20],"poolFreq":"MonthEnd","stated":"2030-01-01"}
    ,{'assets':[["Mortgage"
        ,{"originBalance":2200,"originRate":["fix",0.045],"originTerm":30
          ,"freq":"Monthly","type":"Level","originDate":"2021-02-01"}
          ,{"currentBalance":2200
          ,"currentRate":0.08
          ,"remainTerm":20
          ,"status":"current"}]]}
    ,(("acc01",{"balance":0}),)
    ,(("A",{"A-1":
        {"balance":400
         ,"rate":0.09
         ,"originBalance":400
         ,"originRate":0.07
         ,"startDate":"2021-06-15"
         ,"rateType":{"Fixed":0.08}
         ,"bondType":{"Sequential":None}
         ,"maturityDate":"2025-01-01"}
        ,"A-2":
        {"balance":600
         ,"rate":0.08
         ,"originBalance":600
         ,"originRate":0.07
         ,"startDate":"2021-06-15"
         ,"rateType":{"Fixed":0.08}
         ,"bondType":{"Sequential":None}
        ,"maturityDate":"2026-01-01"}
       })
      ,("B",{"balance":1000
             ,"rate":0.0
             ,"originBalance":1000
             ,"originRate":0.07
             ,"startDate":"2020-01-03"
             ,"rateType":{"Fixed":0.00}
             ,"bondType":{"Equity":None}
             }))
    ,(("trusteeFee",{"type":{"fixFee":30}}),)
    ,{"amortizing":[
         ["payFee","acc01",['trusteeFee']]
         ,["accrueAndPayIntByGroup","acc01","A","byStartDate"]
         ,["payPrinByGroup","acc01","A","byStartDate"]
         ,["payPrin","acc01",["B"]]
         ,["payIntResidual","acc01","B"]
     ]}
    ,[["CollectedInterest","acc01"]
      ,["CollectedPrincipal","acc01"]
      ,["CollectedPrepayment","acc01"]
      ,["CollectedRecoveries","acc01"]]
    ,None
    ,None
    ,None
    ,None
    ,("PreClosing","Amortizing")
    )

In [52]:
localAPI = API(EnginePath.LOCAL,check=False)

Connecting engine server -> http://localhost:8081

✅Connected, local lib:0.28.7, server:0.28.9

In [67]:
fundingPlan = [("2022-04-02","A","acc01"
                      ,{"balance":600
                         ,"rate":0.08
                         ,"name":"A-3"
                         ,"originBalance":600
                         ,"originRate":0.07
                         ,"startDate":"2022-04-02"
                         ,"rateType":{"Fixed":0.08}
                         ,"bondType":{"Sequential":None}
                        ,"maturityDate":"2026-01-01"}
                      )]


r = localAPI.run(test01
                 ,runAssump = [
                     ("issueBond",*fundingPlan)
                     ,("report",{"dates":"MonthEnd"})
                 ]
                 ,read=True
                ,debug=False)

Warning Message from server:

In [70]:
r['result']['report']['balanceSheet']

             asset                                              liability  \
             acc01 Pool Performing Pool Defaulted Pool Recovery         A
reportDate
2021-03-31    0.00         2200.00            0.0           0.0   1000.00
2021-04-30    0.00         2200.00            0.0           0.0   1000.00
2021-05-31    0.00         2200.00            0.0           0.0   1000.00
2021-06-30    0.00         2200.00            0.0           0.0   1000.00
2021-07-31    0.00         2200.00            0.0           0.0   1000.00
2021-08-31    0.00         2200.00            0.0           0.0   1000.00
2021-09-30    0.00         2200.00            0.0           0.0   1000.00
2021-10-31    0.00         2200.00            0.0           0.0   1000.00
2021-11-30    0.00         2200.00            0.0           0.0   1000.00
2021-12-31    0.00         2200.00            0.0           0.0   1000.00
2022-01-31  117.86         2096.80            0.0           0.0   1000.00
2022-02-28  117.86         1992.91            0.0           0.0    969.57
2022-03-31  117.86         1888.33            0.0           0.0    857.94
2022-04-30  117.86         1783.05            0.0           0.0    748.48
2022-05-31  117.85         1677.08            0.0           0.0    635.53
2022-06-30  117.86         1570.39            0.0           0.0    521.99
2022-07-31  117.85         1463.00            0.0           0.0    407.56
2022-08-31  117.85         1354.90            0.0           0.0    292.47
2022-09-30  117.86         1246.07            0.0           0.0    176.60
2022-10-31  117.85         1136.52            0.0           0.0     59.90
2022-11-30  117.86         1026.23            0.0           0.0      0.00
2022-12-31  117.85          915.22            0.0           0.0      0.00
2023-01-31  117.86          803.46            0.0           0.0      0.00
2023-02-28  117.86          690.95            0.0           0.0      0.00
2023-03-31  117.85          577.70            0.0           0.0      0.00
2023-04-30  117.86          463.69            0.0           0.0      0.00
2023-05-31  117.86          348.92            0.0           0.0      0.00
2023-06-30  117.86          233.38            0.0           0.0      0.00
2023-07-31  117.85          117.08            0.0           0.0      0.00
2023-08-31  117.86            0.00            0.0           0.0      0.00

                                                                      equity
                  B Accured Int:A Accured Int:B Fee Due:trusteeFee Net Asset
reportDate
2021-03-31  1000.00          0.00           0.0                0.0    200.00
2021-04-30  1000.00          0.00           0.0                0.0    200.00
2021-05-31  1000.00          0.00           0.0                0.0    200.00
2021-06-30  1000.00          3.44           0.0               30.0    166.56
2021-07-31  1000.00         10.57           0.0               30.0    159.43
2021-08-31  1000.00         17.69           0.0               30.0    152.31
2021-09-30  1000.00         24.58           0.0               30.0    145.42
2021-10-31  1000.00         31.70           0.0               30.0    138.30
2021-11-30  1000.00         38.59           0.0               30.0    131.41
2021-12-31  1000.00         45.71           0.0               30.0    124.29
2022-01-31  1000.00         52.83           0.0               30.0    131.83
2022-02-28  1000.00          1.77           0.0                0.0    139.43
2022-03-31  1000.00          2.13           0.0                0.0    146.12
2022-04-30  1000.00          1.63           0.0                0.0    150.80
2022-05-31  1000.00          1.52           0.0                0.0    157.88
2022-06-30  1000.00          1.14           0.0                0.0    165.12
2022-07-31  1000.00          0.98           0.0                0.0    172.31
2022-08-31  1000.00          0.70           0.0                0.0    179.58
2022-09-30  1000.00          0.38           0.0                0.0    186.95
2022-10-31  1000.00          0.14           0.0                0.0    194.33
2022-11-30   942.45          0.00           0.0                0.0    201.64
2022-12-31   824.59          0.00           0.0                0.0    208.48
2023-01-31   706.74          0.00           0.0                0.0    214.58
2023-02-28   588.88          0.00           0.0                0.0    219.93
2023-03-31   471.02          0.00           0.0                0.0    224.53
2023-04-30   353.17          0.00           0.0                0.0    228.38
2023-05-31   235.31          0.00           0.0                0.0    231.47
2023-06-30   117.45          0.00           0.0                0.0    233.79
2023-07-31     0.00          0.00           0.0                0.0    234.93
2023-08-31     0.00          0.00           0.0                0.0    117.86

In [47]:
readBondsCf(r['bonds'])

BondGroup        A                                                    \
Bond           A-1                                      A-2
Field      balance interest principal  rate    cash balance interest
date
2021-07-26  400.00     0.00      0.00  0.09    0.00  600.00     0.00
2021-08-20  400.00     0.00      0.00  0.09    0.00  600.00     0.00
2021-09-20  400.00     0.00      0.00  0.09    0.00  600.00     0.00
2021-10-20  400.00     0.00      0.00  0.09    0.00  600.00     0.00
2021-11-20  400.00     0.00      0.00  0.09    0.00  600.00     0.00
2021-12-20  400.00     0.00      0.00  0.09    0.00  600.00     0.00
2022-01-20  400.00     0.00      0.00  0.09    0.00  600.00     0.00
2022-02-20  369.57    24.60     30.43  0.09   55.03  600.00    32.83
2022-03-20  257.94     2.55    111.63  0.09  114.18  600.00     3.68
2022-04-20    0.00     1.97    257.94  0.09  259.91  148.48     4.07
2022-05-20     NaN      NaN       NaN   NaN     NaN   35.53     0.97
2022-06-20     NaN      NaN       NaN   NaN     NaN    0.00     0.24
2022-07-20     NaN      NaN       NaN   NaN     NaN     NaN      NaN
2022-08-20     NaN      NaN       NaN   NaN     NaN     NaN      NaN
2022-09-20     NaN      NaN       NaN   NaN     NaN     NaN      NaN
2022-10-20     NaN      NaN       NaN   NaN     NaN     NaN      NaN
2022-11-20     NaN      NaN       NaN   NaN     NaN     NaN      NaN
2022-12-20     NaN      NaN       NaN   NaN     NaN     NaN      NaN
2023-01-20     NaN      NaN       NaN   NaN     NaN     NaN      NaN
2023-02-20     NaN      NaN       NaN   NaN     NaN     NaN      NaN
2023-03-20     NaN      NaN       NaN   NaN     NaN     NaN      NaN
2023-04-20     NaN      NaN       NaN   NaN     NaN     NaN      NaN
2023-05-20     NaN      NaN       NaN   NaN     NaN     NaN      NaN
2023-06-20     NaN      NaN       NaN   NaN     NaN     NaN      NaN
2023-07-20     NaN      NaN       NaN   NaN     NaN     NaN      NaN
2023-08-20     NaN      NaN       NaN   NaN     NaN     NaN      NaN
2023-09-20     NaN      NaN       NaN   NaN     NaN     NaN      NaN

BondGroup                                                                    \
Bond                                   A-3
Field      principal  rate    cash balance interest principal  rate    cash
date
2021-07-26      0.00  0.08    0.00     NaN      NaN       NaN   NaN     NaN
2021-08-20      0.00  0.08    0.00     NaN      NaN       NaN   NaN     NaN
2021-09-20      0.00  0.08    0.00     NaN      NaN       NaN   NaN     NaN
2021-10-20      0.00  0.08    0.00     NaN      NaN       NaN   NaN     NaN
2021-11-20      0.00  0.08    0.00     NaN      NaN       NaN   NaN     NaN
2021-12-20      0.00  0.08    0.00     NaN      NaN       NaN   NaN     NaN
2022-01-20      0.00  0.08    0.00     NaN      NaN       NaN   NaN     NaN
2022-02-20      0.00  0.08   32.83     NaN      NaN       NaN   NaN     NaN
2022-03-20      0.00  0.08    3.68     NaN      NaN       NaN   NaN     NaN
2022-04-20    451.52  0.08  455.59  600.00     2.36      0.00  0.08    2.36
2022-05-20    112.95  0.08  113.92  600.00     3.94      0.00  0.08    3.94
2022-06-20     35.53  0.08   35.77  521.99     4.07     78.01  0.08   82.08
2022-07-20       NaN   NaN     NaN  407.56     3.43    114.43  0.08  117.86
2022-08-20       NaN   NaN     NaN  292.47     2.76    115.09  0.08  117.85
2022-09-20       NaN   NaN     NaN  176.60     1.98    115.87  0.08  117.85
2022-10-20       NaN   NaN     NaN   59.90     1.16    116.70  0.08  117.86
2022-11-20       NaN   NaN     NaN    0.00     0.40     59.90  0.08   60.30
2022-12-20       NaN   NaN     NaN     NaN      NaN       NaN   NaN     NaN
2023-01-20       NaN   NaN     NaN     NaN      NaN       NaN   NaN     NaN
2023-02-20       NaN   NaN     NaN     NaN      NaN       NaN   NaN     NaN
2023-03-20       NaN   NaN     NaN     NaN      NaN       NaN   NaN     NaN
2023-04-20       NaN   NaN     NaN     NaN      NaN       NaN   NaN     NaN
2023-05-20       NaN   NaN     NaN     NaN      NaN       NaN   NaN     NaN
2023-06-20       NaN   NaN     NaN     NaN      NaN       NaN   NaN     NaN
2023-07-20       NaN   NaN     NaN     NaN      NaN       NaN   NaN     NaN
2023-08-20       NaN   NaN     NaN     NaN      NaN       NaN   NaN     NaN
2023-09-20       NaN   NaN     NaN     NaN      NaN       NaN   NaN     NaN

BondGroup         B
Bond              -
Field       balance interest principal rate    cash
date
2021-07-26  1000.00     0.00      0.00    0    0.00
2021-08-20  1000.00     0.00      0.00    0    0.00
2021-09-20  1000.00     0.00      0.00    0    0.00
2021-10-20  1000.00     0.00      0.00    0    0.00
2021-11-20  1000.00     0.00      0.00    0    0.00
2021-12-20  1000.00     0.00      0.00    0    0.00
2022-01-20  1000.00     0.00      0.00    0    0.00
2022-02-20  1000.00     0.00      0.00    0    0.00
2022-03-20  1000.00     0.00      0.00    0    0.00
2022-04-20  1000.00     0.00      0.00    0    0.00
2022-05-20  1000.00     0.00      0.00    0    0.00
2022-06-20  1000.00     0.00      0.00    0    0.00
2022-07-20  1000.00     0.00      0.00    0    0.00
2022-08-20  1000.00     0.00      0.00    0    0.00
2022-09-20  1000.00     0.00      0.00    0    0.00
2022-10-20  1000.00     0.00      0.00    0    0.00
2022-11-20   942.45     0.00     57.55    0   57.55
2022-12-20   824.59     0.00    117.86    0  117.86
2023-01-20   706.74     0.00    117.85    0  117.85
2023-02-20   588.88     0.00    117.86    0  117.86
2023-03-20   471.02     0.00    117.86    0  117.86
2023-04-20   353.17     0.00    117.85    0  117.85
2023-05-20   235.31     0.00    117.86    0  117.86
2023-06-20   117.45     0.00    117.86    0  117.86
2023-07-20     0.00     0.41    117.45    0  117.86
2023-08-20     0.00   117.85      0.00    0  117.85
2023-09-20     0.00   117.86      0.00    0  117.86

In [71]:
r['accounts']['acc01'].loc["2022-04-01":"2022-04-28"]

            balance  change                    memo
date
2022-04-02   717.86  600.00  <IssuanceProceeds:A-3>
2022-04-20   717.86    0.00  <SeqPayFee:trusteeFee>
2022-04-20   709.46   -8.40              <PayInt:A>
2022-04-20     0.00 -709.46             <PayPrin:A>
2022-04-20     0.00    0.00             <PayPrin:B>
2022-04-20     0.00    0.00            <PayYield:B>

In [49]:
r['bonds']['A']['A-3']

,balance,interest,principal,rate,cash,intDue,intOverInt,factor,memo
date,,,,,,,,,
2022-04-20,600.00,2.36,0.00,0.08,2.36,0,0,1.000000,"[<PayInt:A-3>, <PayPrin:A-3>]"
2022-05-20,600.00,3.94,0.00,0.08,3.94,0,0,1.000000,"[<PayInt:A-3>, <PayPrin:A-3>]"
2022-06-20,521.99,4.07,78.01,0.08,82.08,0,0,0.869983,"[<PayInt:A-3>, <PayPrin:A-3>]"
2022-07-20,407.56,3.43,114.43,0.08,117.86,0,0,0.679267,"[<PayInt:A-3>, <PayPrin:A-3>]"
2022-08-20,292.47,2.76,115.09,0.08,117.85,0,0,0.487450,"[<PayInt:A-3>, <PayPrin:A-3>]"
2022-09-20,176.60,1.98,115.87,0.08,117.85,0,0,0.294333,"[<PayInt:A-3>, <PayPrin:A-3>]"
2022-10-20,59.90,1.16,116.70,0.08,117.86,0,0,0.099833,"[<PayInt:A-3>, <PayPrin:A-3>]"
2022-11-20,0.00,0.40,59.90,0.08,60.30,0,0,0.000000,"[<PayInt:A-3>, <PayPrin:A-3>]"

In [57]:
r.keys()

{'bonds': Empty DataFrame
 Columns: [Balance Defaults, Interest Defaults, Original Balance, Total]
 Index: [],
 'status': Empty DataFrame
 Columns: [Date, From, To]
 Index: [],
 'waterfallInspect': None,
 'logs':     Type                                       Comment
 0  Error  issueBond:Missing Account Name in Deal:acc02
 1  Error      issueBond:Existing Bond Name in Deal:A-1}

In [73]:
*{"A":1,"B":2}.keys()

SyntaxError: can't use starred expression here (512273257.py, line 1)