## Run Asset Pool 2

In [8]:
from absbox import API,EnginePath

localAPI = API(EnginePath.DEV, lang='english',check=False)

Connecting engine server -> https://absbox.org/api/dev

✅Connected, local lib:0.26.4, server:0.27.6

### Pool

In `Pool` , it will have a field named `assets` ,which contains a list of `assets`

In [9]:
mortgage1 = ["Mortgage"
            ,{"originBalance": 12000.0
            ,"originRate": ["fix",0.045]
            ,"originTerm": 40
            ,"freq": "monthly"
            ,"type": "level"
            ,"originDate": "2021-02-01"}
            ,{"currentBalance": 10000.0
            ,"currentRate": 0.075
            ,"remainTerm": 30
            ,"status": "current"}]

mortgage2 = ["Mortgage"
            ,{"originBalance": 8000.0
            ,"originRate": ["fix",0.045]
            ,"originTerm": 25
            ,"freq": "monthly"
            ,"type": "level"
            ,"originDate": "2021-02-01"}
            ,{"currentBalance": 6000.0
            ,"currentRate": 0.075
            ,"remainTerm": 15
            ,"status": "current"}]

myPool = {'assets':[ mortgage1, mortgage2  ],
         'cutoffDate':"2022-03-01"}

### Assumption on Pool Level

User can set assumption on pool level ,which suggests the assumption will be applied to all the assets in the pool.

In [10]:
r = localAPI.runPool(myPool
                  ,poolAssump=("Pool",("Mortgage",{"CDR":0.01},None,None,None)
                                    ,None
                                    ,None)
                  ,read=True)

r['PoolConsol'][0].head(10)

,Balance,Principal,Interest,Prepayment,Default,Recovery,Loss,WAC,BorrowerNum,PrepayPenalty,CumPrincipal,CumPrepay,CumDelinq,CumDefault,CumRecovery,CumLoss
Date,,,,,,,,,,,,,,,,
2022-03-01,13891.98,693.78,91.15,0,11.24,0,11.24,0.075,None,None,693.78,0,0,11.24,0,11.24
2022-04-01,13182.62,697.52,86.74,0,11.84,0,11.84,0.075,None,None,1391.30,0,0,23.08,0,23.08
2022-05-01,12470.45,701.30,82.31,0,10.87,0,10.87,0.075,None,None,2092.60,0,0,33.95,0,33.95
2022-06-01,11754.74,705.08,77.87,0,10.63,0,10.63,0.075,None,None,2797.68,0,0,44.58,0,44.58
2022-07-01,11036.14,708.90,73.40,0,9.70,0,9.70,0.075,None,None,3506.58,0,0,54.28,0,54.28
2022-08-01,10313.99,712.74,68.90,0,9.41,0,9.41,0.075,None,None,4219.32,0,0,63.69,0,63.69
2022-09-01,9588.63,716.57,64.40,0,8.79,0,8.79,0.075,None,None,4935.89,0,0,72.48,0,72.48
2022-10-01,8860.27,720.45,59.87,0,7.91,0,7.91,0.075,None,None,5656.34,0,0,80.39,0,80.39
2022-11-01,8128.38,724.34,55.32,0,7.55,0,7.55,0.075,None,None,6380.68,0,0,87.94,0,87.94
2022-12-01,7393.41,728.27,50.75,0,6.70,0,6.70,0.075,None,None,7108.95,0,0,94.64,0,94.64
2023-01-01,6654.92,732.19,46.16,0,6.30,0,6.30,0.075,None,None,7841.14,0,0,100.94,0,100.94
2023-02-01,5913.11,736.14,41.55,0,5.67,0,5.67,0.075,None,None,8577.28,0,0,106.61,0,106.61
2023-03-01,5168.39,740.18,36.92,0,4.54,0,4.54,0.075,None,None,9317.46,0,0,111.15,0,111.15
2023-04-01,4834.54,329.45,32.27,0,4.40,0,4.40,0.075,None,None,4454.43,0,0,84.92,0,84.92
2023-05-01,4499.31,331.24,30.19,0,3.99,0,3.99,0.075,None,None,4785.67,0,0,88.91,0,88.91
2023-06-01,4162.45,333.03,28.09,0,3.83,0,3.83,0.075,None,None,5118.70,0,0,92.74,0,92.74
2023-07-01,3824.19,334.83,25.99,0,3.43,0,3.43,0.075,None,None,5453.53,0,0,96.17,0,96.17
2023-08-01,3484.30,336.63,23.88,0,3.26,0,3.26,0.075,None,None,5790.16,0,0,99.43,0,99.43
2023-09-01,3142.87,338.46,21.75,0,2.97,0,2.97,0.075,None,None,6128.62,0,0,102.40,0,102.40
2023-10-01,2799.99,340.29,19.62,0,2.59,0,2.59,0.075,None,None,6468.91,0,0,104.99,0,104.99
2023-11-01,2455.49,342.12,17.48,0,2.38,0,2.38,0.075,None,None,6811.03,0,0,107.37,0,107.37
2023-12-01,2109.49,343.98,15.33,0,2.02,0,2.02,0.075,None,None,7155.01,0,0,109.39,0,109.39
2024-01-01,1761.87,345.83,13.17,0,1.79,0,1.79,0.075,None,None,7500.84,0,0,111.18,0,111.18
2024-02-01,1412.67,347.70,11.00,0,1.50,0,1.50,0.075,None,None,7848.54,0,0,112.68,0,112.68
2024-03-01,1061.96,349.59,8.82,0,1.12,0,1.12,0.075,None,None,8198.13,0,0,113.80,0,113.80
2024-04-01,709.58,351.48,6.63,0,0.90,0,0.90,0.075,None,None,8549.61,0,0,114.70,0,114.70
2024-05-01,355.61,353.39,4.43,0,0.58,0,0.58,0.075,None,None,8903.00,0,0,115.28,0,115.28
2024-06-01,0.00,355.31,2.22,0,0.30,0,0.30,0.075,None,None,9258.31,0,0,115.58,0,115.58

### Assumption on Asset Level

In [11]:
assetLevelAssump = ("ByIndex"
                      ,([0],(("Mortgage",{"CDR":0.01},None,None,None)
                                    ,None
                                    ,None))
                       ,([1],(("Mortgage",None,{"CPR":0.01},None,None)
                                    ,None
                                    ,None))
                      )

r = localAPI.runPool(myPool
                  ,poolAssump=assetLevelAssump
                  ,read=True)

r['PoolConsol'][0].head()

,Balance,Principal,Interest,Prepayment,Default,Recovery,Loss,WAC,BorrowerNum,PrepayPenalty,CumPrincipal,CumPrepay,CumDelinq,CumDefault,CumRecovery,CumLoss
Date,,,,,,,,,,,,,,,,
2022-03-01,13891.98,693.78,91.15,4.02,7.22,0,7.22,0.075,None,None,693.78,4.02,0,7.22,0,7.22
2022-04-01,13182.62,697.52,86.74,4.12,7.72,0,7.72,0.075,None,None,1391.30,8.14,0,14.94,0,14.94
2022-05-01,12470.45,701.30,82.31,3.66,7.21,0,7.21,0.075,None,None,2092.60,11.80,0,22.15,0,22.15
2022-06-01,11754.74,705.08,77.87,3.45,7.18,0,7.18,0.075,None,None,2797.68,15.25,0,29.33,0,29.33
2022-07-01,11036.14,708.90,73.40,3.01,6.69,0,6.69,0.075,None,None,3506.58,18.26,0,36.02,0,36.02

### Cumulative Stats

User can annotate the `HistoryDefaults` which suggusts as of the `cutoffDate`, how much balance is in status of `Default`

In [ ]:
myPool2 = {'assets':[ mortgage1, mortgage2  ],
           'cutoffDate':"2022-03-01"
           ,'issuanceStat':{"HistoryDefaults":200,"HistoryLoss":50}}

r = localAPI.runPool(myPool2
                  ,poolAssump=("Pool",("Mortgage",{"CDR":0.01},None,None,None)
                                    ,None
                                    ,None)
                  ,read=True)

r['PoolConsol'][0].head()